#!/bin/bash 

#─▄███▄──▄███▄─
#▐████████████▌
#─████████████─
#──▀████████▀──
#─────▀██▀─────
#┊NEZAK ‿ @TH3NK
#┊@AAH_MD ‿ @TH3SS
#---------------------------------------------------------------------
cd $(cd $(dirname $0); pwd)
RED='\033[0;31m'
SMAY='\033[0;36m' 
GREEN='\033[0;32m'
Yellow='\033[0;33m'
LSAMAY='\033[01;49m'
WHITB='\033[01;90m'
WHITEC='\033[01;91m'
CNIL='\033[0m'
Version=`lsb_release -rs | cut -f1 -d"."`

if [ "$Version" == "18" ];then
echo -e "${GREEN}
─▄███▄──▄███▄─
▐████████████▌
─████████████─
──▀████████▀──
─────▀██▀─────
┊NEZAK ‿ @TH3NK
تم تطوير وبرمجة السورس من قبل علي محمد
┊@AAH_MD ‿ @TH3SS
 ---------------------------------------------------------------------${CNIL}"
echo -e "${RED}| للاسف لايمكنك تنصيب السورس ع نظام اوبنتو {${Version}} يجب ان يكون على اصدار  اقل مثلا  ${SMAY}14 او 16
${CNIL}";
echo -e "${RED}| Sorry Canot install Source on Ubuntu {${Version}} Please install system To Ubuntu ${SMAY}14 or 16 ${RED} For Run The Source Th3Neyzk 
${CNIL}";
exit;
fi


if [ ! -f "./TG" ]; then
echo -e "${RED}
¦
¦ CAUTION:${WHITB} Your Not Dwonload TG .
¦ NOW I Run File ${Yellow}./run${WHITB} To install ${SMAY}Source TH3NEYZK${CNIL} . \n
\n\n"
chmod +x ./ins
./ins
exit;
fi

if [ ! -f "./inc/Token.txt" ]; then
echo -e "${RED}
¦
¦ CAUTION:${WHITB} Your Token Bot Not Found .
¦ NOW I Run File ${SMAY}./RUN.lua${WHITB} To Enter Data For You Bot${CNIL}. \n
\n\n"
lua ./inc/Run.lua
exit;
else
TOKEN=`cat ./inc/Token.txt`
BOTID=`echo $TOKEN | cut -f1 -d":"`
Sudo=$(redis-cli get ${BOTID}:SUDO_ID:)
if [[ $Sudo == "" ]]; then
rm -fr ./inc/Token.txt
lua ./inc/Run.lua
exit;
fi
fi


chmod +x ./TG  
Loops=0
if [ "$1" == "R" ]; then
while [[ $Loops -le 5 ]]; do
sleep 1s
sudo rm -fr ~/.telegram-cli
./TG -s ./inc/Run.lua --bot=$TOKEN
let Plas=Loops+1
redis-cli SETEX $TOKEN 3 $Plas
Loops=`redis-cli GET ${TOKEN}`
echo $Loops
if [[ $Loops == 5 ]]; then
curl "https://api.telegram.org/bot${TOKEN}/sendmessage" -F "chat_id=${Sudo}" -F "text=THESOURCE-Reloaded-${COUNTER}-times" &>/dev/null
screen -X -S neyzk quit
fi
done
else 
if [[ $Loops == 0 ]]; then
if ! screen -list | grep -q "neyzk"; then
screen -S neyzk ./run R
else
screen -X -S neyzk quit
screen -S neyzk ./run R
fi
fi
fi

